### ISSUE TITLE
Maps: search suggestion order

### ISSUE THREAD

**Issue by aayushi14** [climatetree/places-microservice#35]
To reproduce: Click on "Maps" -> in search bar, write "se" -> scroll down the popped up suggestions.

The suggestions should be in alphabetical order. (sea, seb, sec, sed)

<img width="376" alt="map search order" src="https://user-images.githubusercontent.com/33564949/77973013-fe107480-72c0-11ea-8364-a72f43548120.PNG">

**Comment by colemclark1** [comment]
I've update the database stored function to return the names in alphabetical order. You can see the reflected changes on the current site www.climatetree.wiki

**Comment by aayushi14** [comment]
Looks good!
